source 'https://rubygems.org'

gem 'sinatra'
gem 'sidekiq'
gem 'warbler'
# gem 'aws-sdk', '< 2'

group :development, :test do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
